# 13City站点的配置文件
site_name: "13City"
form_fields:
  medium: "medium_sel[4]"
  codec: "codec_sel[4]"
  audio_codec: "audiocodec_sel[4]"
  resolution: "standard_sel[4]"
  team: "team_sel[4]"
  processing: "processing_sel[4]"

mappings:
  type:
    "Movies": "401"
    "电影": "401"
    "Driver": "401"
    "Movie": "401"
    "TV Series": "402"
    "电视剧": "402"
    "Playlet": "402"
    "短剧": "402"
    "MV": "406"
    "演唱会": "406"
    "Music Video": "406"
    "TV Shows": "403"
    "综艺": "403"
    "Sports": "403"
    "体育": "403"
    "体育竞技": "403"
    "Animations": "405"
    "动漫": "405"
    "动画": "405"
    "Anime": "405"
    "漫画": "405"
    "Cartoon": "405"
    "游戏": "405"
    "Game": "405"
    "Music Videos": "406"
    "演唱会、MV": "406"
    "学习": "408"
    "Study": "408"
    "Music": "408"
    "音乐": "408"
    "有声书": "409"
    "Audiobook": "409"
    "电子书&有声读物": "409"
    "电子书": "409"
    "Ebook": "409"
    "Documentaries": "413"
    "纪录片": "413"
    "记录片": "413"
    "其他": "401"
    "Misc": "401"
    "未知": "401"
    "Unknown": "401"
    "default": "401"

  medium:
    'UHD Blu-ray': '1'
    'Blu-ray': '1'
    'BD': '1'
    'Remux': '3'
    'Encode': '7'
    'WEB-DL': '10'
    'WEB': '10'
    'WEBRip': '12'
    'TVrip': '12'
    'HDTV': '5'
    'DVD': '6'
    'HD DVD': '2'
    'DVDR': '6'
    'CD': '8'
    'Track': '9'
    'MiniBD': '4'
    'MVC': '4'
    'ProRes': '7'
    'Xvid': '6'
    'Other': '13'
    'default': '13'

  codec:
    'VVC': '2'
    'AV1': '5'
    'AVC': '1'
    'H.264': '1'
    'x264': '1'
    'HEVC': '2'
    'H.265': '2'
    'x265': '2'
    'MPEG-2': '3'
    'MPEG-4': '3'
    'VC-1': '4'
    'VP9': '5'
    'VPB': '5'
    'Xvid': '6'
    'Other': '7'
    'default': '7'

  audio_codec:
    'TrueHD Atmos': '9'
    'DTS:X': '3'
    'DTS-HD MA': '3'
    'DTS-HD HR': '3'
    'DDP': '7'
    'DD+': '7'
    'E-AC3': '7'
    'Atmos': '9'
    'TrueHD': '8'
    'DTS': '3'
    'AC3': '7'
    'DD': '7'
    'LPCM': '10'
    'FLAC': '1'
    'APE': '2'
    'M4A': '1'
    'ALAC': '1'
    'WAV': '4'
    'MP3': '4'
    'AAC': '6'
    'OGG': '5'
    'OPUS': '5'
    'DSD': '10'
    'PCM': '10'
    'EAC3': '7'
    'Other': '11'
    'default': '11'

  resolution:
    '8K': '1'
    '4320p': '1'
    '4K': '2'
    '2160p': '2'
    'UHD': '2'
    '1080p': '3'
    '1080i': '4'
    '720p': '4'
    '720i': '4'
    'FHD': '3'
    '540p': '4'
    'QHD': '2'
    '1440p': '2'
    '2K': '2'
    '480p': '5'
    '480i': '5'
    'SD': '5'
    'Other': '5'
    'default': '5'

  processing:
    "中国（含港澳台）": "1"
    "中国": "1"
    "CN": "1"
    "中国大陆": "1"
    "香港": "1"
    "HK": "1"
    "台湾": "1"
    "TW": "1"
    "港台": "1"
    "日本": "2"
    "JPN": "2"
    "JP": "2"
    "泰国": "3"
    "印度": "4"
    "IN": "4"
    "韩国": "5"
    "KR": "5"
    "欧美": "6"
    "美国": "6"
    "US": "6"
    "欧洲": "6"
    "EU": "6"
    "Other（其他）": "7"
    "其他": "7"
    "default": "7"

  source:
    '大陆': '1'
    '台湾': '2'
    '香港': '3'
    '日本': '4'
    '韩国': '5'
    '欧美': '6'
    '印度': '7'
    'default': '8'

  team:
    "13City": "1"
    "AilMWeb": "2"
    "52pt": "3"
    "HHWEB": "4"
    "CHDWEB": "5"
    "FRDS": "6"
    "MTeam": "7"
    "QHstudIo": "8"
    "PTerWEB": "9"
    "rainweb": "10"
    "SewageWeb": "12"
    "UBWEB": "13"
    "ZmWeb": "14"
    "ADWeb": "15"
    "UBits": "16"
    "WiKi": "17"
    "Other": "11"
    "default": "11"

  tag:
    "完结": 9
    "分集": 8
    "粤语": 13
    "多语": 10
    "国语": 5
    "中字": 6
    "中英双字": 14
    "4K": 12
    "1080p": 11
    "HDR": 7
    "DIY": 4
    "红叶转载": 19
    "有声图书": 15
    "default": null
