# CrabPT站点的配置文件
site_name: "CrabPT"
form_fields:
  medium: "source_sel[4]"
  codec: "codec_sel[4]"
  audio_codec: "audiocodec_sel[4]"
  resolution: "standard_sel[4]"
  team: "team_sel[4]"
  processing: "processing_sel[4]"
  special_codec: "codec_sel[6]"
  special_audio_codec: "audiocodec_sel[6]"
  special_team: "team_sel[6]"
  special_processing: "processing_sel[6]"

mappings:
  type:
    "Movies": "401"
    "电影": "401"
    "Driver": "401"
    "Movie": "401"
    "TV Series": "402"
    "电视剧": "402"
    "Playlet": "413"
    "短剧": "413"
    "Music": "408"
    "音乐": "408"
    "Animations": "405"
    "动漫": "405"
    "动画": "405"
    "Anime": "405"
    "MV": "406"
    "演唱会": "406"
    "Music Video": "406"
    "TV Shows": "403"
    "综艺": "403"
    "Sports": "407"
    "体育": "407"
    "体育竞技": "407"
    "Documentaries": "404"
    "记录片": "404"
    "纪录片": "404"
    "漫画": "415"
    "Cartoon": "415"
    "游戏": "414"
    "Game": "414"
    "学习": "412"
    "Study": "412"
    "有声书": "411"
    "Audiobook": "411"
    "电子书": "410"
    "Ebook": "410"
    "其他": "409"
    "Misc": "409"
    "未知": "409"
    "Unknown": "409"
    "default": "409"

  medium:
    'UHD Blu-ray': '3'
    'Blu-ray': '2'
    'BD': '2'
    'Remux': '4'
    'Encode': '5'
    'WEB-DL': '6'
    'WEBRip': '5'
    'WEB': '6'
    'HDTV': '7'
    'TVrip': '7'
    'CD': '8'
    'Track': '8'
    'MVC': '9'
    'ProRes': '10'
    'Xvid': '11'
    'default': '1'

  codec:
    'H.265': '3'
    'HEVC': '3'
    'x265': '3'
    'H.264': '2'
    'AVC': '2'
    'x264': '2'
    'VC-1': '14'
    'MPEG-2': '15'
    'MPEG-4': '15'
    'H.266': '4'
    'VVC': '4'
    'AV1': '6'
    'VP9': '5'
    'default': '1'

  audio_codec:
    'TrueHD Atmos': '26'
    'DTS:X': '8'
    'DTS-HD MA': '17'
    'DTS-HD HR': '22'
    'DDP': '4'
    'DD+': '4'
    'E-AC3': '4'
    'Atmos': '26'
    'TrueHD': '6'
    'DTS': '5'
    'AC3': '3'
    'DD': '3'
    'LPCM': '7'
    'FLAC': '10'
    'APE': '12'
    'WAV': '11'
    'M4A': '13'
    'MPEG': '9'
    'MP3': '9'
    'AAC': '2'
    'OGG': '21'
    'OPUS': '24'
    'DSD': '23'
    'ALAC': '16'
    'default': '1'

  resolution:
    '8K': '5'
    '4320p': '5'
    '4K': '4'
    '2160p': '4'
    'UHD': '4'
    '1080p': '3'
    '1080i': '3'
    '720p': '2'
    '720i': '2'
    'default': '1'

  processing:
    "中国": "2"
    "CN": "2"
    "中国大陆": "2"
    "香港": "3"
    "HK": "3"
    "台湾": "3"
    "TW": "3"
    "港台": "3"
    "美国": "4"
    "US": "4"
    "欧美": "4"
    "欧洲": "4"
    "EU": "4"
    "日本": "5"
    "JPN": "5"
    "JP": "5"
    "韩国": "6"
    "KR": "6"
    "印度": "7"
    "IN": "7"
    "其他": "1"
    "default": "1"

  team:
    "AGSVWEB": "15"
    "DYZ-WEB": "11"
    "DYZ-Movie": "12"
    "DYZ-TV": "13"
    "UBits": "9"
    "HHWEB": "8"
    "FRDS": "7"
    "XHB": "6"
    "OurBits": "5"
    "WiKi": "4"
    "HDS": "3"
    "CHD": "2"
    "Audiences": "10"
    "ZmWeb": "16"
    "MTeam": "37"
    "HDVWEB": "36"
    "HDHome": "35"
    "QHstudIo": "34"
    "beAst": "33"
    "tlf": "32"
    "FROGWeb": "30"
    "FROG": "29"
    "CMCT": "27"
    "ADWeb": "25"
    "PiGoNF": "23"
    "PigoWeb": "22"
    "PigoHD": "21"
    "HDFans": "20"
    "UBWEB": "19"
    "FFans": "18"
    "Pter": "17"
    "红叶": "38"
    "default": "1"

  format:
    'EPUB': '8'
    'AZW3': '9'
    'MOBI': '10'
    'PDF': '11'
    'ZIP': '12'
    'EPUB/ZAW3/MOBI': '13'
    'TXT': '7'
    'default': '1'

  special_audio_codec:
    'OGG': '14'
    'M4A': '13'
    'AAC': '2'
    'DTS-HD': '15'
    'DTS-HD MA': '17'
    'DSD': '23'
    'Atmos': '26'
    'default': '1'

  special_team:
    "AGSVWEB": "15"
    "DYZ-WEB": "11"
    "DYZ-Movie": "12"
    "DYZ-TV": "13"
    "UBits": "9"
    "HHWEB": "8"
    "FRDS": "7"
    "XHB": "6"
    "OurBits": "5"
    "WiKi": "4"
    "HDS": "3"
    "CHD": "2"
    "Audiences": "10"
    "ZmWeb": "16"
    "红叶": "38"
    "beAst": "33"
    "tlf": "32"
    "FROGWeb": "30"
    "FROG": "29"
    "CMCT": "27"
    "ADWeb": "25"
    "QHstudIo": "24"
    "PiGoNF": "23"
    "PigoWeb": "22"
    "PigoHD": "21"
    "HDFans": "20"
    "UBWEB": "19"
    "FFans": "18"
    "Pter": "17"
    "default": "1"

  tag:
    "合集大包": 19
    "原盘DIY": 4
    "国语": 5
    "粤语": 6
    "中字": 7
    "分集": 9
    "完结": 8
    "HDR": 11
    "特效字幕": 10
    "Dolby Vision": 12
    "Dolby Atmos": 13
    "未完结": 59
    "ASMR": 50
    "武侠": 48
    "灾难": 47
    "冒险": 46
    "奇幻": 45
    "犯罪": 44
    "战争": 43
    "历史": 42
    "纪录": 41
    "恐怖": 40
    "惊悚": 39
    "悬疑": 38
    "动画": 37
    "科幻": 36
    "爱情": 35
    "动作": 34
    "喜剧": 33
    "剧情": 32
    "短剧": 25
    "AGSV": 24
    "Audiences": 23
    "驻站": 22
    "伦理": 20
    "default": null

  special_tag:
    "无限流": 62
    "穿越重生": 61
    "传记名著": 60
    "文学出版": 56
    "外语有声": 55
    "相声评书": 57
    "言情小说": 58
    "灵异悬疑": 30
    "历史军事": 53
    "电台节目": 52
    "传统戏曲": 51
    "都市异能": 31
    "武侠仙侠": 29
    "科幻末日": 28
    "游戏竞技": 27
    "奇幻玄幻": 26
    "知识普及": 17
    "历史架空": 14
    "合集大包": 19
    "中字": 7
    "分集": 9
    "完结": 8
    "军事": 18
    "财经": 16
    "网文": 15
    "未完结": 59
    "轻小说": 54
    "灾难": 47
    "犯罪": 44
    "动画": 37
    "科幻": 36
    "条漫": 21
    "default": null
