# Cspt站点的配置文件
site_name: "Cspt"
form_fields:
  medium: "source_sel[4]"
  codec: "codec_sel[4]"
  audio_codec: "audiocodec_sel[4]"
  resolution: "standard_sel[4]"
  team: "team_sel[4]"

mappings:
  type:
    "Music": "408"
    "音乐": "408"
    "HQ音乐": "408"
    "专辑": "408"
    "音轨": "408"
    "音频": "408"
    "Audio": "408"
    "Sports": "407"
    "体育": "407"
    "MV": "406"
    "演唱会": "406"
    "Music Video": "406"
    "Documentaries": "404"
    "记录片": "404"
    "纪录片": "404"
    "TV Shows": "403"
    "综艺": "403"
    "TV Series": "402"
    "电视剧": "402"
    "Movies": "401"
    "电影": "401"
    "Driver": "401"
    "Movie": "401"
    "Animations": "405"
    "动漫": "405"
    "动画": "405"
    "Anime": "405"
    "软件": "409"
    "图书": "409"
    "学习": "409"
    "游戏": "409"
    "音乐会": "409"
    "资料": "409"
    "其他": "409"
    "Misc": "409"
    "未知": "409"
    "Unknown": "409"
    "default": "409"

  medium:
    'UHD Blu-ray': '8'
    'BluRay': '7'
    'Blu-ray': '7'
    'BD': '7'
    'Remux': '9'
    'Encode': '10'
    'WEB-DL': '11'
    'WEBRip': '10'
    'WEB': '11'
    'HDTV': '12'
    'TVrip': '12'
    'DVD': '13'
    'CD': '14'
    'Track': '15'
    'default': '16'

  codec:
    'H.265': '2'
    'HEVC': '2'
    'x265': '2'
    'H.264': '1'
    'AVC': '1'
    'x264': '1'
    'VC-1': '3'
    'MPEG-2': '4'
    'AV1': '6'
    'default': '5'

  audio_codec:
    'TrueHD Atmos': '11'
    'DTS:X': '16'
    'DTS-HD MA': '17'
    'DDP': '12'
    'DD+': '12'
    'E-AC3': '12'
    'Atmos': '11'
    'TrueHD': '15'
    'DTS': '18'
    'AC3': '13'
    'DD': '13'
    'LPCM': '14'
    'FLAC': '22'
    'AAC': '9'
    'ALAC': '8'
    'APE': '10'
    'M4A': '19'
    'WAV': '20'
    'MP3': '21'
    'default': '23'

  resolution:
    '8K': '8'
    '4320p': '8'
    '4K': '7'
    '2160p': '7'
    'UHD': '7'
    '2K': '10'
    '1440p': '10'
    '1080p': '6'
    '1080i': '6'
    '720p': '5'
    '480p': '4'
    '480i': '4'
    'default': '9'

  team:
    "CSPT": "19"
    "CSWEB": "18"
    "HSPT": "8"
    "HSWEB": "9"
    "default": "5"

  tag:
    "驻站": 23
    "首发": 2
    "DIY": 4
    "国语": 5
    "中字": 6
    "HDR": 7
    "独家": 13
    "自压": 14
    "重制": 15
    "外挂字幕": 16
    "Remux": 10
    "大包": 17
    "超分": 18
    "补帧": 19
    "粤语": 12
    "特效": 20
    "杜比": 11
    "喜剧": 8
    "分集": 21
    "完结": 9
    "儿童": 24
    "Dolby Vision": 11
    "default": null
