# Gtkpw站点的配置文件
site_name: "Gtkpw"
form_fields:
  medium: "medium_sel[4]"
  codec: "codec_sel[4]"
  resolution: "standard_sel[4]"
  team: "team_sel[4]"

mappings:
  type:
    "Movies": "401"
    "电影": "401"
    "Driver": "401"
    "Movie": "401"
    "TV Series": "402"
    "电视剧": "402"
    "TV Shows": "403"
    "综艺": "403"
    "Documentaries": "404"
    "记录片": "404"
    "纪录片": "404"
    "Animations": "405"
    "动漫": "405"
    "动画": "405"
    "Anime": "405"
    "MV": "406"
    "演唱会": "406"
    "Music Video": "406"
    "Sports": "407"
    "体育": "407"
    "Music": "409"
    "音乐": "409"
    "专辑": "409"
    "音轨": "409"
    "音频": "409"
    "Audio": "409"
    "短剧": "410"
    "软件": "410"
    "图书": "410"
    "学习": "410"
    "游戏": "410"
    "音乐会": "410"
    "资料": "410"
    "其他": "410"
    "Misc": "410"
    "未知": "410"
    "Unknown": "410"
    "default": "410"

  medium:
    'UHD Blu-ray': '10'
    'Blu-ray': '1'
    'BluRay': '1'
    'HD DVD': '2'
    'Remux': '3'
    'Encode': '7'
    'MiniBD': '4'
    'WEB-DL': '11'
    'WEB': '11'
    'WEBRip': '7'
    'HDTV': '5'
    'DVDR': '6'
    'CD': '8'
    'Track': '9'
    'default': '5'

  codec:
    'H.265': '6'
    'HEVC': '6'
    'x265': '6'
    'H.264': '1'
    'AVC': '1'
    'x264': '1'
    'VC-1': '2'
    'XviD': '3'
    'MPEG-2': '4'
    'AV1': '7'
    'VP9': '8'
    'default': '5'

  resolution:
    '8K': '6'
    '4320p': '6'
    '4K': '5'
    '2160p': '5'
    '1080p': '1'
    '1080i': '2'
    '720p': '3'
    'SD': '4'
    'default': '4'

  team:
    "CMCT": "6"
    "HDS": "1"
    "CHD": "2"
    "MYSILU": "3"
    "WIKI": "4"
    "MARK": "7"
    "MTEAM": "8"
    "FRDS": "9"
    "PTHOME": "10"
    "BEAST": "11"
    "default": "5"

  tag:
    "首发": 2
    "完结": 9
    "分集": 8
    "粤语": 13
    "多语": 10
    "国语": 5
    "中字": 6
    "中英双字": 14
    "4K": 12
    "1080p": 11
    "HDR": 7
    "DIY": 4
    "红叶转载": 19
    "有声图书": 15
    "default": null
