# HDTime时光站点的配置文件
site_name: "HDTime"
form_fields:
  medium: "medium_sel[4]"
  codec: "codec_sel[4]"
  audio_codec: "audiocodec_sel[4]"
  team: "team_sel[4]"

mappings:
  type:
    "电影": "401"
    "Movies": "401"
    "Movie": "401"
    "剧集": "402"
    "TV Series": "402"
    "电视剧": "402"
    "综艺": "403"
    "TV Shows": "403"
    "纪录片": "404"
    "Documentaries": "404"
    "动漫": "405"
    "Animations": "405"
    "动画": "405"
    "MV": "406"
    "Music Video": "406"
    "音乐": "408"
    "Music": "408"
    "其他": "409"
    "文档": "411"
    "游戏": "410"
    "体育": "407"
    "软件": "414"
    "Blu-Ray原盘": "424"
    "default": "401"

  medium:
    'BluRay': '1'
    'Blu-ray': '1'
    'BD': '1'
    'Blu-ray DIY': '1'
    'Remux': '3'
    'Encode': '7'
    'WEB-DL': '10'
    'WEBRip': '12'
    'WEB': '10'
    'HDTV': '5'
    'DVD': '6'
    'HD DVD': '2'
    'DVDR': '6'
    'CD': '8'
    'Track': '9'
    'MiniBD': '4'
    'Other': '13'
    'default': '13'

  codec:
    'AVC': '1'
    'H.264': '1'
    'x264': '1'
    'HEVC': '12'
    'H.265': '12'
    'x265': '12'
    'x264-10bit': '11'
    'AV1': '15'
    'VP8': '14'
    'VP9': '14'
    'AVS3': '17'
    'Xvid': '3'
    'MPEG-2': '4'
    'VC-1': '2'
    'VVC': '16'
    'H.266': '16'
    'x266': '16'
    'Other': '5'
    'default': '5'

  audio_codec:
    'TrueHD Atmos': '8'
    'TrueHD': '9'
    'DTS-HD': '10'
    'DTS': '3'
    'DD': '11'
    'AC3': '11'
    'DDP': '12'
    'EAC3': '12'
    'LPCM': '13'
    'PCM': '13'
    'FLAC': '1'
    'APE': '2'
    'MP3': '4'
    'OGG': '5'
    'AAC': '6'
    'Audio Vivid': '14'
    'AV3A': '14'
    'OPUS': '15'
    'Other': '7'
    'default': '7'

  team:
    "个人原创": "9"
    "Other": "5"
    "CHD": "2"
    "beAst": "3"
    "WiKi": "4"
    "CMCT": "8"
    "PADTime": "7"
    "VTime": "15"
    "HDT": "12"
    "HDTime": "6"
    "QHstudIo": "16"
    "AilMWeb": "17"
    "HHWEB": "18"
    "default": "5"

  tag:
    "杜比视界": "8"
    "DIY": "4"
    "国语": "5"
    "中字": "6"
    "HDR": "7"
    "default": null
