# Lajidui站点的配置文件
site_name: "Lajidui"
form_fields:
  medium: "medium_sel[4]"
  processing: "processing_sel[4]"
  codec: "codec_sel[4]"
  resolution: "standard_sel[4]"
  audio_codec: "audiocodec_sel[4]"
  source: "source_sel[4]"
  team: "team_sel[4]"

mappings:
  type:
    "Movies": "401"
    "电影": "401"
    "TV Series": "402"
    "电视剧": "402"
    "TV Shows": "403"
    "综艺": "403"
    "Documentaries": "404"
    "记录片": "404"
    "纪录片": "404"
    "Animations": "405"
    "动漫": "405"
    "动画": "405"
    "Music Videos": "406"
    "MV": "406"
    "演唱会": "406"
    "Sports": "407"
    "体育": "407"
    "Audio": "408"
    "音乐": "408"
    "专辑": "408"
    "音轨": "408"
    "音频": "408"
    "Misc": "409"
    "其他": "409"
    "Cartoon": "410"
    "少儿动画": "410"
    "Ebook": "411"
    "电子书": "411"
    "ShortDrama": "412"
    "短剧": "412"
    "Game": "413"
    "游戏": "413"
    "APP": "414"
    "软件": "414"
    "Education": "415"
    "教育视频": "415"
    "Audiobook": "416"
    "有声书": "416"
    "default": "409"

  medium:
    'WEB-DL': '10'
    'Track': '9'
    'CD': '8'
    'DVDR': '6'
    'HDTV': '5'
    'MiniBD': '4'
    'Encode': '7'
    'Remux': '3'
    'HD DVD': '2'
    'Blu-ray': '1'
    'default': '11'

  processing:
    'MKV': '10'
    'MP4': '11'
    'EPUB': '1'
    'PDF': '2'
    'TXT': '3'
    'DOCX': '4'
    'PPTX': '5'
    'XLSX': '6'
    'WPS': '7'
    'AZW3': '8'
    'MOBI': '9'
    'RAR': '12'
    'ZIP': '13'
    '7z': '14'
    'ISO': '16'
    'default': '10'

  codec:
    'AV1': '6'
    'H.265': '7'
    'x265': '7'
    'HEVC': '7'
    'H.264': '1'
    'x264': '1'
    'AVC': '1'
    'VC-1': '2'
    'Xvid': '3'
    'MPEG-2': '4'
    'default': '5'

  resolution:
    '8k': '7'
    '4k': '6'
    '2k': '5'
    '1080p': '1'
    '1080i': '2'
    '720p': '3'
    'SD': '4'
    'default': '8'

  audio_codec:
    'FLAC': '1'
    'APE': '2'
    'DTS': '3'
    'MP3': '4'
    'OGG': '5'
    'AAC': '6'
    'WAV': '8'
    'DTS-HD': '9'
    'TrueHD': '10'
    'LPCM': '11'
    'E-AC-3': '12'
    'DDP': '12'
    'AC-3': '13'
    'DD': '13'
    'default': '7'

  source:
    '大陆': '7'
    '台湾': '2'
    '香港': '8'
    '日本': '10'
    '韩国': '11'
    '欧美': '1'
    '印度': '3'
    'default': '6'

  team:
    "Ourbits": "12"
    "GodDramas": "22"
    "BeiTai": "21"
    "BMDru": "20"
    "LHD": "19"
    "beAst": "18"
    "CatEDU": "17"
    "Pter": "16"
    "AGSVWEB": "15"
    "HDHome": "14"
    "QHstudIo": "13"
    "HDSky": "1"
    "UBits": "11"
    "TJUPT": "10"
    "FRDS": "9"
    "CMCT": "8"
    "ADE": "7"
    "HHWEB": "6"
    "WiKi": "4"
    "原创": "3"
    "CHD": "2"
    "default": "5"

  tag:
    "已刮削": 8
    "DIY": 4
    "国语": 5
    "中字": 6
    "HDR": 7
    "单集": 12
    "粤语": 11
    "杜比": 10
    "完结": 9
    "default": null
