# March三月传媒站点的配置文件
site_name: "March"
form_fields:
  medium: "medium_sel[4]"
  codec: "codec_sel[4]"
  resolution: "standard_sel[4]"
  team: "team_sel[4]"

mappings:
  type:
    "Movies": "401"
    "电影": "401"
    "Driver": "401"
    "Movie": "401"
    "TV Series": "402"
    "电视剧": "402"
    "Playlet": "402"
    "短剧": "402"
    "MV": "406"
    "演唱会": "406"
    "Music Video": "406"
    "TV Shows": "403"
    "综艺": "403"
    "Sports": "403"
    "体育": "403"
    "体育竞技": "403"
    "Animations": "405"
    "动漫": "405"
    "动画": "405"
    "Anime": "405"
    "漫画": "405"
    "Cartoon": "405"
    "游戏": "405"
    "Game": "405"
    "Music Videos": "406"
    "演唱会、MV": "406"
    "学习": "408"
    "Study": "408"
    "Music": "408"
    "音乐": "408"
    "有声书": "409"
    "Audiobook": "409"
    "电子书&有声读物": "409"
    "电子书": "409"
    "Ebook": "409"
    "Documentaries": "404"
    "纪录片": "404"
    "记录片": "404"
    "其他": "409"
    "Misc": "409"
    "未知": "409"
    "Unknown": "409"
    "default": "401"

  medium:
    'UHD Blu-ray': '1'
    'Blu-ray': '1'
    'BD': '1'
    'Blu-ray DIY': '1'
    'Remux': '3'
    'Encode': '7'
    'WEB-DL': '13'
    'WEB': '13'
    'WEBRip': '12'
    'TVrip': '12'
    'HDTV': '5'
    'DVD': '8'
    'HD DVD': '2'
    'DVDR': '8'
    'Other': '4'
    'default': '4'

  codec:
    'VVC': '10'
    'AV1': '10'
    'AVC': '1'
    'H.264': '1'
    'x264': '1'
    'HEVC': '2'
    'H.265': '2'
    'x265': '2'
    'MPEG-2': '4'
    'MPEG-4': '5'
    'VC-1': '6'
    'VP9': '7'
    'VPB': '7'
    'Xvid': '9'
    'Other': '11'
    'default': '11'

  resolution:
    '8K': '8'
    '4320p': '8'
    '4K': '6'
    '2160p': '6'
    'UHD': '6'
    '1080p': '1'
    '1080i': '2'
    '720p': '3'
    '720i': '3'
    'FHD': '1'
    '540p': '3'
    'QHD': '6'
    '1440p': '6'
    '2K': '6'
    '480p': '4'
    '480i': '4'
    'SD': '4'
    'Other': '7'
    'default': '7'

  team:
    "March": "1"
    "3MWEB": "1"
    "CHD": "2"
    "TTG": "3"
    "CMCT": "4"
    "HDSKY": "5"
    "OurBits": "6"
    "M-Team": "7"
    "WIKI": "8"
    "Beast": "9"
    "HHWEB": "10"
    "Other": "11"
    "default": "11"

  tag:
    "DIY": 4
    "国语": 5
    "中字": 6
    "HDR": 7
    "default": null
