# Novahd站点的配置文件
site_name: "Novahd"
form_fields:
  medium: "medium_sel[4]"
  codec: "codec_sel[4]"
  audio_codec: "audiocodec_sel[4]"
  resolution: "standard_sel[4]"
  team: "team_sel[4]"

mappings:
  type:
    "Movies": "401"
    "电影": "401"
    "Driver": "401"
    "Movie": "401"
    "TV Series": "402"
    "电视剧": "402"
    "TV Shows": "402"
    "综艺": "402"
    "Documentaries": "404"
    "记录片": "404"
    "纪录片": "404"
    "Animations": "405"
    "动漫": "405"
    "动画": "405"
    "Anime": "405"
    "MV": "406"
    "演唱会": "406"
    "Music Video": "406"
    "Sports": "407"
    "体育": "407"
    "Music": "409"
    "音乐": "409"
    "专辑": "409"
    "音轨": "409"
    "音频": "409"
    "短剧": "410"
    "软件": "410"
    "图书": "410"
    "学习": "410"
    "游戏": "410"
    "音乐会": "410"
    "资料": "410"
    "其他": "410"
    "Misc": "410"
    "未知": "410"
    "Unknown": "410"
    "default": "410"

  medium:
    'UHD Blu-ray': '10'
    'Blu-ray': '1'
    'BD': '1'
    'Remux': '3'
    'Encode': '7'
    'WEB-DL': '11'
    'WEBRip': '7'
    'WEB': '11'
    'HDTV': '5'
    'TVrip': '5'
    'DVD': '13'
    'CD': '8'
    'Track': '9'
    'default': '16'

  codec:
    'H.265': '6'
    'HEVC': '6'
    'x265': '6'
    'H.264': '1'
    'AVC': '1'
    'x264': '1'
    'VC-1': '2'
    'MPEG-2': '4'
    'default': '5'

  audio_codec:
    'TrueHD Atmos': '8'
    'DTS:X': '14'
    'DTS-HD MA': '13'
    'DDP': '9'
    'DD+': '9'
    'E-AC3': '9'
    'Atmos': '8'
    'TrueHD': '12'
    'DTS': '3'
    'AC3': '10'
    'DD': '10'
    'LPCM': '11'
    'FLAC': '1'
    'AAC': '6'
    'ALAC': '7'
    'APE': '2'
    'M4A': '1'
    'WAV': '1'
    'MP3': '4'
    'default': '15'

  resolution:
    '8K': '6'
    '4320p': '6'
    '4K': '5'
    '2160p': '5'
    'UHD': '5'
    '2K': '5'
    '1440p': '5'
    '1080p': '1'
    '1080i': '2'
    '720p': '3'
    '480p': '4'
    '480i': '4'
    'default': '6'

  team:
    "NOVAHD": "15"
    "NHD": "15"
    "HDSKY": "1"
    "CHD": "2"
    "MYSILU": "3"
    "WIKI": "4"
    "OTHER": "5"
    "FRDS": "6"
    "mUHD-FRDS": "6"
    "MNHD-FRDS": "6"
    "BEAST": "7"
    "CMCT": "8"
    "TLF": "9"
    "M-TEAM": "10"
    "MWeb": "10"
    "BEITAI": "11"
    "AGSV": "12"
    "HDHOME": "13"
    "TTG": "14"
    "NHDWEB": "15"
    "default": "5"

  tag:
    "DIY": 4
    "国语": 5
    "中字": 6
    "HDR": 7
    "连载": 18
    "番组": 17
    "特效": 15
    "杜比": 14
    "大包": 13
    "应求": 12
    "英字": 11
    "完结": 10
    "分集": 9
    "驻站": 8
    "default": null
