# pt0ffcc自由农场站点的配置文件
site_name: "pt0ffcc"
form_fields:
  source: "source_sel[4]"
  resolution: "standard_sel[4]"
  medium: "medium_sel[4]"
  codec: "codec_sel[4]"
  audio_codec: "audiocodec_sel[4]"
  team: "team_sel[4]"

mappings:
  type:
    "电影": "401"
    "Movies": "401"
    "Movie": "401"
    "电视剧": "402"
    "TV Series": "402"
    "剧集": "402"
    "纪录片": "403"
    "Documentaries": "403"
    "综艺": "404"
    "TV Shows": "404"
    "动漫": "405"
    "Animations": "405"
    "动画": "405"
    "音乐视频": "406"
    "Music Videos": "406"
    "MV": "406"
    "无损音乐": "407"
    "HD Music": "407"
    "体育": "408"
    "Sports": "408"
    "学习教育": "427"
    "Education": "427"
    "书籍": "412"
    "book": "412"
    "游戏": "411"
    "Game": "411"
    "网络资源": "410"
    "Resources": "410"
    "其他": "428"
    "Others": "428"
    "default": "428"

  source:
    "内地": "35"
    "中国": "35"
    "CHN": "35"
    "香港": "36"
    "HKG": "36"
    "台湾": "37"
    "TWN": "37"
    "韩国": "39"
    "KOR": "39"
    "欧美": "38"
    "Western": "38"
    "日本": "40"
    "JPN": "40"
    "印度": "41"
    "IND": "41"
    "泰国": "34"
    "Th": "34"
    "其它": "42"
    "Other": "42"
    "default": "42"

  resolution:
    "8K": "1"
    "4320P": "1"
    "4K": "2"
    "2160P": "2"
    "UHD": "2"
    "1080P": "3"
    "1440P": "4"
    "1080I": "5"
    "720P": "6"
    "SD": "7"
    "其它": "14"
    "Other": "14"
    "default": "14"

  medium:
    "Blu-ray": "2"
    "BD": "2"
    'Blu-ray DIY': '2'
    "UHDTV": "3"
    "IPTV": "4"
    "Remux": "5"
    "Encode": "6"
    "HDTV": "7"
    "DVDR": "8"
    "CD": "9"
    "MiniBD": "10"
    "Track": "11"
    "WEB-DL": "12"
    "SACD": "13"
    "HD DVD": "14"
    "3D Blu-ray": "15"
    "UHD Blu-ray": "1"
    "其它": "21"
    "Other": "21"
    "default": "21"

  codec:
    "H.265": "1"
    "HEVC": "1"
    "H.264": "2"
    "AVC": "2"
    "X265": "3"
    "X264": "4"
    "VC-1": "6"
    "MPEG-4": "7"
    "MPEG-2": "8"
    "Xvid": "9"
    "MVC": "10"
    "ProRes": "11"
    "VP8": "12"
    "VP9": "12"
    "AV1": "13"
    "其它": "14"
    "Other": "14"
    "default": "14"

  audio_codec:
    "DTS-HDMA:X 7.1": "10"
    "TrueHD Atmos": "1"
    "FLAC": "9"
    "OPUS": "8"
    "LPCM": "7"
    "DTS-X": "6"
    "TrueHD": "5"
    "AC3": "4"
    "DD": "4"
    "DTS-MA": "2"
    "DTS-HD": "3"
    "DTS-HR": "3"
    "DTS": "14"
    "PCM": "17"
    "DSD": "16"
    "APE": "15"
    "AAC": "13"
    "MP3": "12"
    "WAV": "11"
    "OGG": "21"
    "其它": "22"
    "Other": "22"
    "default": "22"

  team:
    "FFWEB": "15"
    "其它": "14"
    "Other": "14"
    "default": "14"

  tag:
    "连载": "12"
    "DIY": "4"
    "国语": "5"
    "中字": "6"
    "HDR": "7"
    "短剧": "8"
    "3D": "11"
    "default": null
