# Ptzone站点的配置文件
site_name: "Ptzone"
form_fields:
  medium: "medium_sel[4]"
  codec: "codec_sel[4]"
  audio_codec: "audiocodec_sel[4]"
  resolution: "standard_sel[4]"
  team: "team_sel[4]"

mappings:
  type:
    "Movies": "401"
    "电影": "401"
    "Driver": "401"
    "Movie": "401"
    "TV Series": "402"
    "电视剧": "402"
    "TV Shows": "403"
    "综艺": "403"
    "Documentaries": "404"
    "记录片": "404"
    "纪录片": "404"
    "Animations": "405"
    "动漫": "405"
    "动画": "405"
    "Anime": "405"
    "MV": "406"
    "演唱会": "406"
    "Music Video": "406"
    "Music": "406"
    "音乐": "406"
    "专辑": "406"
    "音轨": "406"
    "音频": "406"
    "Sports": "407"
    "体育": "407"
    "Software": "410"
    "软件": "410"
    "Games": "411"
    "游戏": "411"
    "短剧": "409"
    "图书": "409"
    "学习": "409"
    "音乐会": "409"
    "资料": "409"
    "其他": "409"
    "Misc": "409"
    "未知": "409"
    "Unknown": "409"
    "default": "409"

  medium:
    'UHD Blu-ray': '10'
    'Blu-ray': '1'
    'BluRay': '1'
    'HD DVD': '2'
    'Remux': '3'
    'WEB-DL': '4'
    'WEB': '4'
    'WEBRip': '7'
    'HDTV': '5'
    'DVDR': '6'
    'Encode': '7'
    'CD': '8'
    'Track': '9'
    'default': '7'

  codec:
    'H.265': '6'
    'HEVC': '6'
    'x265': '6'
    'H.264': '1'
    'AVC': '1'
    'x264': '1'
    'VC-1': '2'
    'MPEG-2': '3'
    'MPEG-4': '4'
    'default': '5'

  audio_codec:
    'DTS-HD MA': '10'
    'DTS-HD': '13'
    'TrueHD': '14'
    'DDP': '12'
    'EAC3': '12'
    'DD+': '12'
    'AC3': '11'
    'DD': '11'
    'DTS': '3'
    'FLAC': '1'
    'APE': '2'
    'MP3': '4'
    'OGG': '5'
    'AAC': '6'
    'WAV': '15'
    'default': '7'

  resolution:
    '8K': '5'
    '4320p': '5'
    '4K': '6'
    '2160p': '6'
    '1080p': '1'
    '1080i': '2'
    '720p': '3'
    'SD': '4'
    'default': '4'

  team:
    "PTZWeb": "6"
    "HDS": "1"
    "CHD": "2"
    "MYSILU": "3"
    "WIKI": "4"
    "default": "5"

  tag:
    "DIY": 4
    "国语": 5
    "中字": 6
    "HDR": 7
    "分集": 8
    "完结": 9
    "default": null
