# Qingwapt站点的配置文件
site_name: "Qingwapt"
form_fields:
  medium: "source_sel[4]"
  codec: "codec_sel[4]"
  audio_codec: "audiocodec_sel[4]"
  resolution: "standard_sel[4]"
  team: "team_sel[4]"

mappings:
  type:
    "Movies": "401"
    "电影": "401"
    "Driver": "401"
    "Movie": "401"
    "TV Series": "402"
    "电视剧": "402"
    "TV Shows": "403"
    "综艺": "403"
    "Animations": "405"
    "动漫": "405"
    "动画": "405"
    "Anime": "405"
    "MV": "406"
    "演唱会": "406"
    "Music Video": "406"
    "Sport": "407"
    "体育": "407"
    "Music": "408"
    "音乐": "408"
    "专辑": "408"
    "音轨": "408"
    "音频": "408"
    "Audio": "408"
    "Documentaries": "404"
    "记录片": "404"
    "纪录片": "404"
    "短剧": "412"
    "其他": "409"
    "Misc": "409"
    "未知": "409"
    "Unknown": "409"
    "default": "409"

  medium:
    'BluRay': '8'
    'Blu-ray': '8'
    'BD': '8'
    'Blu-ray DIY': '8'
    'Remux': '9'
    'Encode': '10'
    'MiniBD': '11'
    'WEB-DL': '7'
    'WEBRip': '10'
    'WEB': '7'
    'HDTV': '4'
    'TVrip': '4'
    'DVD': '2'
    'CD': '3'
    'UHD Blu-ray': '1'
    'Track': '5'
    'default': '6'

  codec:
    'H.265': '6'
    'HEVC': '6'
    'x265': '6'
    'H.264': '1'
    'AVC': '1'
    'x264': '1'
    'AV1': '7'
    'VC-1': '2'
    'MPEG-2': '4'
    'Xvid': '3'
    'MPEG-4': '3'
    'VP9': '8'
    'default': '5'

  audio_codec:
    'DTS:X': '9'
    'DTS-X': '9'
    'DTS': '14'
    'DTS-HD MA': '10'
    'DTS-HD HRA': '21'
    'TrueHD Atmos': '11'
    'Atmos': '11'
    'TrueHD': '12'
    'LPCM': '13'
    'DD': '15'
    'AC3': '15'
    'DDP/E-AC3': '16'
    'E-AC3': '16'
    'DD+': '16'
    'FLAC': '1'
    'AAC': '17'
    'APE': '18'
    'WAV': '19'
    'MP3': '4'
    'M4A': '8'
    'OPUS': '20'
    'AV3A': '22'
    'default': '7'

  resolution:
    '8K': '6'
    '4320p': '6'
    '4K': '7'
    '2160p': '7'
    'UHD': '7'
    '2K': '8'
    '1440p': '8'
    '1080p': '1'
    '1080i': '2'
    '720p': '3'
    'SD': '4'
    '480p': '4'
    '480i': '4'
    'default': '5'

  team:
    "FROG": "6"
    "FROGE": "7"
    "FROGWeb": "8"
    "CatEDU": "10"
    "default": "5"

  tag:
    "VCB-Studio": 2
    "儿童片": 17
    "LGBTQ+": 19
    "中字": 6
    "特效字幕": 20
    "国语": 5
    "粤语": 8
    "完结": 14
    "系列合集": 10
    "原生原盘": 11
    "DIY": 4
    "Remux": 15
    "杜比视界": 12
    "HDR10+": 13
    "HDR": 7
    "default": null
