# sewerpt下水道站点的配置文件
site_name: "sewerpt"
form_fields:
  medium: "medium_sel[4]"
  codec: "codec_sel[4]"
  audio_codec: "audiocodec_sel[4]"
  resolution: "standard_sel[4]"
  team: "team_sel[4]"

mappings:
  type:
    "电影": "401"
    "Movies": "401"
    "Movie": "401"
    "电视剧": "402"
    "TV Series": "402"
    "剧集": "402"
    "纪录片": "404"
    "Documentaries": "404"
    "综艺": "403"
    "TV Shows": "403"
    "动漫": "405"
    "Animations": "405"
    "动画": "405"
    "音乐": "408"
    "Music": "408"
    "其他": "409"
    "Misc": "409"
    "default": "409"

  medium:
    "Blu-ray": "1"
    "BD": "1"
    'BluRay': '1'
    'Blu-ray DIY': '1'
    "Remux": "3"
    "Encode": "7"
    "WEB-DL": "10"
    "HDTV": "5"
    "DVD": "6"
    "HD DVD": "2"
    "DVDR": "6"
    "CD": "8"
    "MiniBD": "4"
    "Other": "11"
    "default": "11"

  codec:
    "AVC": "1"
    "H.264": "1"
    "x264": "1"
    "HEVC": "6"
    "H.265": "6"
    "x265": "6"
    "VC-1": "2"
    "Xvid": "3"
    "MPEG-2": "4"
    "Other": "5"
    "default": "5"

  audio_codec:
    "FLAC": "1"
    "APE": "2"
    "DTS": "3"
    "MP3": "4"
    "OGG": "5"
    "AAC": "6"
    "Other": "7"
    "AC3": "8"
    "DD": "8"
    "E-AC3": "11"
    "ALAC": "9"
    "WAV": "10"
    "TrueHD Atmos": "12"
    "TrueHD": "13"
    "DTS-HD MA": "14"
    "DTS:X": "15"
    "LPCM": "16"
    "AV3A": "17"
    "OPUS": "18"
    "default": "7"

  resolution:
    "480p": "2"
    "720p": "3"
    "1080p": "1"
    "1080i": "1"
    "2K": "4"
    "1440p": "4"
    "4K": "5"
    "2160p": "5"
    "8K": "6"
    "4320p": "6"
    "default": "1"

  team:
    "SewageWeb": "1"
    "Other": "5"
    "default": "5"

  tag:
    "冷门/低分": "11"
    "国语": "5"
    "粤语": "15"
    "中字": "6"
    "原盘": "10"
    "DIY": "4"
    "HDR": "7"
    "短剧": "13"
    "完结": "12"
    "高码率": "16"
    "杜比": "14"
    "分集": "8"
    "default": null
