# Upxin站点的配置文件
site_name: "Upxin"
form_fields:
  medium: "medium_sel"
  codec: "codec_sel"
  audio_codec: "audiocodec_sel"
  resolution: "standard_sel"
  processing: "processing_sel"
  team: "team_sel"

mappings:
  type:
    "Movies": "401"
    "电影": "401"
    "Driver": "401"
    "Movie": "401"
    "TV Series": "402"
    "电视剧": "402"
    "TV Shows": "403"
    "综艺": "403"
    "Documentaries": "404"
    "记录片": "404"
    "纪录片": "404"
    "Animations": "405"
    "动漫": "405"
    "动画": "405"
    "Anime": "405"
    "MV": "406"
    "Music Videos": "406"
    "演唱会": "406"
    "Sports": "407"
    "体育": "407"
    "HQ Audio": "408"
    "音乐": "408"
    "无损音乐": "408"
    "音频": "408"
    "Games": "410"
    "游戏": "410"
    "其他": "411"
    "Misc": "411"
    "未知": "411"
    "Unknown": "411"
    "default": "411"

  medium:
    'Blu-ray': '1'
    'BD': '1'
    'BluRay': '1'
    'Blu-ray DIY': '1'
    'Remux': '3'
    'Remux TV': '12'
    'Encode': '7'
    'Encode TV': '14'
    'WEB-DL': '10'
    'WEBRip': '10'
    'WEB': '10'
    'WEB-DL TV': '13'
    'WEBRip TV': '13'
    'HDTV': '5'
    'TVrip': '5'
    'DVD': '6'
    'MiniBD': '4'
    'CD': '8'
    'UHD Blu-ray': '11'
    'UHD Remux': '15'
    'UHD Remux TV': '16'
    'Track': '9'
    'default': '0'

  codec:
    'H.265': '14'
    'HEVC': '14'
    'x265': '14'
    'H.264': '1'
    'AVC': '1'
    'x264': '16'
    'VC-1': '2'
    'XviD': '3'
    'MPEG-2': '18'
    'MPEG': '18'
    'default': '5'

  audio_codec:
    'DTS:X': '16'
    'DTS-HD MA': '1'
    'DTS-HDMA': '1'
    'TrueHD': '3'
    'LPCM': '11'
    'DTS': '4'
    'AC3': '2'
    'EAC3': '2'
    'DD+': '2'
    'DD': '2'
    'AAC': '6'
    'FLAC': '7'
    'APE': '10'
    'WAV': '17'
    'MPEG': '18'
    'MP3': '18'
    'default': '13'

  resolution:
    '8K': '5'
    '4320p': '5'
    '4K': '5'
    '2160p': '5'
    'UHD': '5'
    '1080p': '1'
    '1080i': '2'
    '720p': '3'
    '720i': '3'
    '480p': '4'
    '480i': '4'
    'SD': '4'
    'iPad': '6'
    'default': '0'

  processing:
    "中国": "1"
    "CN": "1"
    "大陆": "1"
    "中国内地": "1"
    "香港": "3"
    "HK": "3"
    "台湾": "3"
    "TW": "3"
    "港台": "3"
    "美国": "2"
    "US": "2"
    "欧美": "2"
    "欧洲": "2"
    "EU": "2"
    "日本": "4"
    "JPN": "4"
    "JP": "4"
    "韩国": "5"
    "KR": "5"
    "印度": "6"
    "IN": "6"
    "东南亚": "8"
    "SEA": "8"
    "default": "7"

  team:
    "HDU": "2"
    "default": "5"
