# Xingyunge站点的配置文件
site_name: "Xingyunge"
form_fields:
  medium: "medium_sel[4]"
  codec: "codec_sel[4]"
  audio_codec: "audiocodec_sel[4]"
  resolution: "standard_sel[4]"
  team: "team_sel[4]"

mappings:
  type:
    "Movies": "401"
    "电影": "401"
    "TV Series": "402"
    "电视剧": "402"
    "TV Shows": "403"
    "综艺": "403"
    "Documentaries": "404"
    "记录片": "404"
    "纪录片": "404"
    "Animations": "405"
    "动漫": "405"
    "动画": "405"
    "MV": "406"
    "演唱会": "406"
    "Sports": "407"
    "体育": "407"
    "Music": "408"
    "音乐": "408"
    "专辑": "408"
    "音轨": "408"
    "音频": "408"
    "短剧": "410"
    "软件": "410"
    "图书": "410"
    "学习": "410"
    "游戏": "410"
    "音乐会": "410"
    "资料": "410"
    "其他": "409"
    "default": "409"

  medium:
    'Blu-ray': '1'
    'BD': '1'
    'BluRay': '1'
    'Blu-ray DIY': '1'
    'Remux': '3'
    'Encode': '7'
    'WEB-DL': '4'
    'WEBRip': '7'
    'WEB': '4'
    'HDTV': '5'
    'TVrip': '5'
    'DVD': '6'
    'CD': '8'
    'UHD Blu-ray': '2'
    'Track': '9'
    'default': '10'

  codec:
    'H.265': '2'
    'HEVC': '2'
    'x265': '2'
    'H.264': '1'
    'AVC': '1'
    'x264': '1'
    'AV1': '5'
    'VC-1': '3'
    'MPEG-2': '4'
    'default': '6'

  audio_codec:
    'TrueHD Atmos': '12'
    'DTS:X': '7'
    'DTS-HD MA': '6'
    'DDP': '11'
    'DD+': '11'
    'E-AC3': '11'
    'Atmos': '12'
    'TrueHD': '8'
    'DTS': '5'
    'AC3': '10'
    'DD': '10'
    'LPCM': '9'
    'FLAC': '1'
    'AAC': '14'
    'ALAC': '15'
    'APE': '13'
    'M4A': '4'
    'WAV': '3'
    'MP3': '2'
    'OPUS': '17'
    'default': '16'

  resolution:
    '8K': '5'
    '4320p': '5'
    '4K': '4'
    '2160p': '4'
    'UHD': '4'
    '1080p': '3'
    '1080i': '3'
    '720p': '2'
    '480p': '1'
    '480i': '1'
    'default': '6'

  team:
    "WiKi": "4"
    "MySiLU": "3"
    "HDS": "1"
    "CHD": "2"
    "rainweb": "7"
    "rain": "6"
    "StarfallWeb": "8"
    "AGSVWEB": "9"
    "Starfall": "10"
    "default": "5"

  tag:
    "国语": 5
    "中字": 6
    "补帧": 20
    "超分": 19
    "特效": 18
    "大包": 17
    "应求": 16
    "英字": 15
    "韩剧": 14
    "美剧": 13
    "粤语": 12
    "特效字幕": 9
    "杜比视界": 8
    "DV": 8
    "DIY": 4
    "HDR": 7
    "原生": 24
    "完结": 11
    "分集": 10
    "default": null
