site_name: "CHDBits"

form_fields:
  category: "type"
  source: "source_sel"
  medium: "medium_sel"
  resolution: "standard_sel"
  video_codec: "codec_sel"
  audio_codec: "audiocodec_sel"

source_parsers:
  source_params:
    type:
      source_key: "类型"
    medium:
      source_key: "媒介"
    video_codec:
      source_key: "视频编码"
    audio_codec:
      source_key: "音频编码"
    resolution:
      source_key: "分辨率"
    team:
      source_key: "制作组"

  standard_keys:
    type:
      "Movies": "category.movie"
      "TV Series": "category.tv_series"
      "Documentaries": "category.documentaries"
      "Animations": "category.animations"
      "TV Shows": "category.tv_shows"
      "Sports": "category.sports"
      "Music": "category.music"
      "HQ Audio": "category.music"
      "Game": "category.game"

    medium:
      "Blu-ray": "medium.bluray"
      "UHD Blu-ray": "medium.uhd_bluray"
      "Remux": "medium.remux"
      "Encode": "medium.encode"
      "HDTV": "medium.hdtv"
      "WEB-DL": "medium.webdl"
      "CD": "medium.cd"
      "Other": "medium.other"

    video_codec:
      "H.265": "video.h265"
      "H.264/AVC": "video.h264"
      "VC-1": "video.vc1"
      "MPEG-2": "video.mpeg2"
      "MPEG-4": "video.mpeg4"
      "AV1": "video.av1"
      "Other": "video.other"

    audio_codec:
      "DTS-HD": "audio.dts_hd_ma"
      "True-HD": "audio.truehd"
      "LPCM": "audio.lpcm"
      "DTS": "audio.dts"
      "AC3": "audio.ac3"
      "AAC": "audio.aac"
      "FLAC": "audio.flac"
      "APE": "audio.ape"
      "WAV": "audio.wav"
      "ALAC": "audio.alac"
      "Other": "audio.other"

    resolution:
      "8K": "resolution.r4320p"
      "4K": "resolution.r2160p"
      "1080p": "resolution.r1080p"
      "1080i": "resolution.r1080i"
      "720p": "resolution.r720p"
      "Other": "resolution.other"

    source:
      "美剧": "source.western"
      "日剧": "source.japan"
      "港剧": "source.hongkong"
      "韩剧": "source.korea"
      "英剧": "source.uk"
      "台剧": "source.taiwan"
      "国剧": "source.china"
      "新剧": "source.singapore"
      "马剧": "source.malaysia"

    team:
      "CHDBits": "team.chdbits"
      "SGNB": "team.sgnb"
      "REMUX": "team.remux"
      "CHDTV": "team.chdtv"
      "CHDPAD": "team.chdpad"
      "CHDWEB": "team.chdweb"
      "CHDHKTV": "team.chdhktv"
      "OneHD": "team.onehd"
      "blucook": "team.blucook"
      "KAN": "team.kan"
      "JKCT": "team.jkct"
      "BMDru": "team.bmdru"
      "Destiny": "team.destiny"

    tag:
      "官方": "tag.官方"
      "首发": "tag.首发"
      "独占": "tag.独占"
      "限转": "tag.限转"
      "国语": "tag.国语"
      "DIY": "tag.DIY"
      "中字": "tag.中字"
      "特效": "tag.特效"
      "default": null
