# HDDolby站点的配置文件
# 基于三层解耦模型重构，包含source_parsers和标准化的mappings

site_name: "HDDolby"

# 表单字段定义 - 定义站点上传表单中各字段的标识符
form_fields:
  category: "type"
  medium: "medium_sel"
  video_codec: "codec_sel"
  audio_codec: "audiocodec_sel"
  resolution: "standard_sel"
  team: "team_sel"
  tags[]: "tags[]"

# 标准化键映射 - 定义源文本到标准化键的映射规则
# source_parsers部分：定义如何从原始数据解析出标准化参数
source_parsers:
  source_params:
    type:
      source_key: "类型"
    medium:
      source_key: "媒介"
    video_codec:
      source_key: "编码"
    audio_codec:
      source_key: "音频编码"
    resolution:
      source_key: "分辨率"
    team:
      source_key: "制作组"
    tags[]:
      source_key: "标签"

  # 标准化键映射规则（从原始文本到标准化键）
  # 将站点下拉菜单的文本映射到全局标准化键
  standard_keys:
    type:
      "Movies电影": "category.movie"
      "TV Series电视剧": "category.tv_series"
      "TV Shows综艺": "category.tv_shows"
      "Documentaries纪录片": "category.documentaries"
      "Animations动漫": "category.animation"
      "Music Videos": "category.mv"
      "Sports体育": "category.sports"
      "HQ Audio音乐": "category.music"
      "Games游戏": "category.game"
      "Study学习": "category.study"
      "Others其他": "category.other"

    medium:
      "UHD": "medium.uhd_bluray"
      "Blu-ray": "medium.bluray"
      "Remux": "medium.remux"
      "Encode": "medium.encode"
      "WEB-DL": "medium.webdl"
      "FEED": "medium.feed"
      "HDTV": "medium.hdtv"
      "Webrip": "medium.webrip"
      "HD DVD": "medium.hddvd"
      "DVD": "medium.dvd"
      "CD": "medium.cd"
      "Other": "medium.other"

    video_codec:
      "H.265/HEVC": "video.h265"
      "H.264/AVC": "video.h264"
      "H.266/VVC": "video.h266"
      "AV1": "video.av1"
      "VP9": "video.vp9"
      "AVS3": "video.avs3"
      "AVS+": "video.avs_plus"
      "AVS2": "video.avs2"
      "VC-1": "video.vc1"
      "MPEG-2": "video.mpeg2"
      "Other": "video.other"

    audio_codec:
      "DTS-HD MA": "audio.dts_hd_ma"
      "TrueHD": "audio.truehd"
      "DTS-X": "audio.dtsx"
      "LPCM": "audio.lpcm"
      "DTS": "audio.dts"
      "DD/AC3": "audio.ac3"
      "DDP/EAC3": "audio.ddp"
      "AAC": "audio.aac"
      "Opus": "audio.opus"
      "FLAC": "audio.flac"
      "APE": "audio.ape"
      "WAV": "audio.wav"
      "MP3": "audio.mp3"
      "M4A": "audio.m4a"
      "AV3A": "audio.av3a"
      "AVSA": "audio.avsa"
      "MPEG": "audio.mpeg"
      "Other": "audio.other"

    resolution:
      "4320/8K": "resolution.r4320p"
      "2160p/4K": "resolution.r2160p"
      "1080p": "resolution.r1080p"
      "1080i": "resolution.r1080i"
      "720p": "resolution.r720p"
      "Others": "resolution.other"

    team:
      "Dream": "team.dream"
      "DBTV": "team.dbtv"
      "QHstudIo": "team.qhstudio"
      "CornerMV": "team.cornermv"
      "Telesto": "team.telesto"
      "MTeam": "team.mteam"
      "WiKi": "team.wiki"
      "FRDS": "team.frds"
      "HDo": "team.hdo"
      "beAst": "team.beast"
      "CHD": "team.chd"
      "CMCT": "team.cmct"
      "PTHome": "team.pthome"
      "Other": "team.other"

    tag:
      "国语": "tag.国语"
      "粤语": "tag.粤语"
      "日语": "tag.日语"
      "韩语": "tag.韩语"
      "特效": "tag.特效"
      "中字": "tag.中字"
      "连载": "tag.连载"
      "完结": "tag.完结"
      "DIY": "tag.DIY"
      "DOLBY VISION": "tag.Dolby_Vision"
      "HDR10": "tag.hdr10"
      "HDR10+": "tag.hdr10plus"
      "HLG": "tag.hlg"
      "HDR Vivid": "tag.hdr_vivid"
      "高码率": "tag.高码率"
      "高帧率": "tag.高帧率"
      "应求": "tag.应求"

# 参数映射规则 - 定义如何将标准化键映射到站点特定参数
mappings:
  type:
    "category.movie": "401"
    "category.tv_series": "402"
    "category.tv_shows": "403"
    "category.documentaries": "404"
    "category.animation": "405"
    "category.mv": "406"
    "category.sports": "407"
    "category.music": "408"
    "category.game": "410"
    "category.study": "411"
    "category.other": "409"
    "default": "401"

  medium:
    "medium.uhd_bluray": "1"
    "medium.bluray": "2"
    "medium.remux": "3"
    "medium.uhd_remux": "1"
    "medium.remux_tv": "12"
    "medium.uhd_remux_tv": "16"
    "medium.encode": "10"
    "medium.encode_tv": "14"
    "medium.webdl": "6"
    "medium.webdl_tv": "13"
    "medium.feed": "12"
    "medium.hdtv": "5"
    "medium.webrip": "7"
    "medium.hddvd": "4"
    "medium.dvd": "8"
    "medium.cd": "9"
    "medium.other": "11"
    "default": "11"

  video_codec:
    "video.h265": "2"
    "video.h264": "1"
    "video.h266": "13"
    "video.av1": "11"
    "video.vp9": "12"
    "video.avs3": "14"
    "video.avs_plus": "15"
    "video.avs2": "16"
    "video.vc1": "5"
    "video.mpeg2": "6"
    "video.other": "7"
    "default": "7"

  audio_codec:
    "audio.dts_hd_ma": "1"
    "audio.truehd": "2"
    "audio.dtsx": "15"
    "audio.lpcm": "3"
    "audio.dts": "4"
    "audio.ac3": "5"
    "audio.ddp": "14"
    "audio.aac": "6"
    "audio.opus": "13"
    "audio.flac": "7"
    "audio.ape": "8"
    "audio.wav": "9"
    "audio.mp3": "10"
    "audio.m4a": "11"
    "audio.av3a": "16"
    "audio.avsa": "17"
    "audio.mpeg": "18"
    "audio.other": "12"
    "default": "12"

  resolution:
    "resolution.r4320p": "6"
    "resolution.r2160p": "1"
    "resolution.r1080p": "2"
    "resolution.r1080i": "3"
    "resolution.r720p": "4"
    "resolution.other": "5"
    "default": "5"

  team:
    "team.dream": "1"
    "team.dbtv": "10"
    "team.qhstudio": "12"
    "team.cornermv": "13"
    "team.telesto": "14"
    "team.mteam": "2"
    "team.wiki": "4"
    "team.frds": "7"
    "team.hdo": "9"
    "team.beast": "11"
    "team.chd": "5"
    "team.cmct": "6"
    "team.pthome": "3"
    "team.hdu": "2"
    "team.other": "8"
    "default": "8"

  tag:
    "tag.国语": "gy"
    "tag.粤语": "yy"
    "tag.日语": "ja"
    "tag.韩语": "ko"
    "tag.特效": "tx"
    "tag.中字": "zz"
    "tag.连载": "lz"
    "tag.完结": "wj"
    "tag.DIY": "diy"
    "tag.Dolby_Vision": "db"
    "tag.hdr10": "hdr10"
    "tag.hdr10plus": "hdrm"
    "tag.hlg": "hlg"
    "tag.hdr_vivid": "hdrv"
    "tag.高码率": "hq"
    "tag.高帧率": "hfr"
    "tag.应求": "yq"
    "default": null
