site_name: "HHCLUB"

form_fields:
  category: "type"
  source: "source_sel"
  medium: "medium_sel"
  resolution: "standard_sel"
  video_codec: "codec_sel"
  audio_codec: "audiocodec_sel"

source_parsers:
  source_params:
    type:
      source_key: "类型"
    medium:
      source_key: "媒介"
    video_codec:
      source_key: "视频编码"
    audio_codec:
      source_key: "音频编码"
    resolution:
      source_key: "分辨率"
    team:
      source_key: "制作组"
    source:
      source_key: "处理"

  standard_keys:
    type:
      "电影": "category.movie"
      "动漫": "category.animation"
      "电视剧": "category.tv_series"
      "纪录片": "category.documentaries"
      "综艺": "category.tv_shows"
      "体育": "category.sports"
      "短剧": "category.playlet"
      "其他": "category.other"

    source:
      "美剧": "source.western"
      "日剧": "source.japan"
      "韩剧": "source.korea"
      "港剧": "source.hongkong"
      "台剧": "source.taiwan"
      "大陆剧": "source.china"
      "英剧": "source.uk"
      "其他": "source.other"

    medium:
      "UHD Blu-ray": "medium.uhd_bluray"
      "FHD Blu-ray": "medium.bluray"
      "UHD REMUX": "medium.remux"
      "Remux": "medium.remux"
      "Encode": "medium.encode"
      "WEB-DL": "medium.web_dl"
      "HDTV": "medium.hdtv"
      "DVDR": "medium.dvdr"
      "CD": "medium.cd"
      "Track": "medium.track"

    video_codec:
      "HEVC/H265/x265": "video.h265"
      "AVC/H264/x264": "video.h264"
      "VC-1": "video.vc1"
      "MPEG-2": "video.mpeg2"
      "VP8/9": "video.vp9"
      "Other": "video.other"

    audio_codec:
      "TrueHD Atmos": "audio.truehd_atmos"
      "TrueHD": "audio.truehd"
      "DTS-X": "audio.dtsx"
      "DTS-HD|MA": "audio.dts_hd_ma"
      "DTS-HD|HR": "audio.dts_hd_hr"
      "DTS": "audio.dts"
      "DD/AC3": "audio.ac3"
      "DDP/EAC3": "audio.ddp"
      "AAC": "audio.aac"
      "LPCM/PCM": "audio.lpcm"
      "MP2/3": "audio.mp3"
      "FLAC": "audio.flac"
      "APE": "audio.ape"
      "OGG": "audio.ogg"
      "Opus": "audio.opus"
      "WAV": "audio.wav"
      "TAA": "audio.taa"
      "ALAC": "audio.alac"
      "Other": "audio.other"

    resolution:
      "4320p/8K": "resolution.r4320p"
      "2160p/4K": "resolution.r2160p"
      "1080p": "resolution.r1080p"
      "1080i": "resolution.r1080i"
      "720p": "resolution.r720p"
      "Other": "resolution.other"

    team:
      "HHWEB": "team.hhweb"
      "Other": "team.other"

    tag:
      "官方": "tag.官方"
      "完结": "tag.完结"
      "原创": "tag.原创"
      "禁转": "tag.禁转"
      "首发": "tag.首发"
      "国语": "tag.国语"
      "粤语": "tag.粤语"
      "中字": "tag.中字"
      "特效": "tag.特效"
      "DIY": "tag.DIY"
      "杜比视界": "tag.Dolby_Vision"
      "HDR": "tag.HDR"
      "HLG": "tag.HLG"
      "应求": "tag.应求"
      "转载": "tag.转载"
