site_name: "PTerClub"

form_fields:
  medium: "source_sel"
  source: "team_sel"
  category: "type"
  jinzhuan: "jinzhuan"
  guanfang: "guanfang"
  guoyu: "guoyu"
  yueyu: "yueyu"
  zhongzi: "zhongzi"
  ensub: "ensub"
  yingqiu: "yingqiu"
  diy: "diy"
  pr: "pr"
  bim: "bim"
  mp: "mp"

source_parsers:
  source_params:
    type:
      source_key: "类型"
    medium:
      source_key: "媒介"
    source:
      source_key: "区域"
    team:
      source_key: "制作组"

  standard_keys:
    type:
      "电影": "category.movie"
      "电视剧": "category.tv_series"
      "动画": "category.animation"
      "综艺": "category.tv_shows"
      "音乐短片": "category.mv"
      "音乐": "category.music"
      "舞台演出": "category.stage"
      "纪录片": "category.documentaries"
      "体育": "category.sports"
      "电子书": "category.ebook"
      "软件": "category.software"
      "学习": "category.study"
      "其它": "category.other"

    medium:
      "UHD Discs": "medium.uhd_bluray"
      "BD Discs": "medium.bluray"
      "Remux": "medium.remux"
      "HDTV": "medium.hdtv"
      "WEB-DL": "medium.webdl"
      "Encode": "medium.encode"
      "DVD Discs": "medium.dvdr"
      "FLAC": "medium.flac"
      "WAV": "medium.wav"
      "ISO": "medium.iso"
      "PDF": "medium.pdf"
      "PUB": "medium.pub"
      "AZW": "medium.azw"
      "MOBI": "medium.mobi"
      "Other": "medium.other"

    source:
      "大陆 (Mainland,CHN)": "source.china"
      "香港 (HKG,CHN)": "source.hongkong"
      "台湾 (TWN,CHN)": "source.taiwan"
      "欧美 (Western)": "source.western"
      "韩国 (KOR)": "source.korea"
      "日本 (JPN)": "source.japan"
      "印度 (IND)": "source.india"
      "其它 (Other)": "source.other"

mappings:
  type:
    "category.movie": "401"
    "category.tv_series": "404"
    "category.animation": "403"
    "category.tv_shows": "405"
    "category.mv": "413"
    "category.music": "406"
    "category.stage": "418"
    "category.documentaries": "402"
    "category.sports": "407"
    "category.ebook": "408"
    "category.software": "410"
    "category.study": "411"
    "category.other": "412"
    "default": "401"

  medium:
    "medium.uhd_bluray": "1"
    "medium.bluray": "2"
    "medium.remux": "3"
    "medium.hdtv": "4"
    "medium.webdl": "5"
    "medium.encode": "6"
    "medium.dvdr": "7"
    "medium.flac": "8"
    "medium.wav": "9"
    "medium.iso": "10"
    "medium.pdf": "11"
    "medium.pub": "12"
    "medium.azw": "13"
    "medium.mobi": "14"
    "medium.other": "15"
    "default": "15"

  source:
    "source.china": "1"
    "source.hongkong": "2"
    "source.taiwan": "3"
    "source.western": "4"
    "source.korea": "5"
    "source.japan": "6"
    "source.india": "7"
    "source.other": "8"
    "default": "8"

  tag:
    "tag.国语": "yes"
    "tag.粤语": "yes"
    "tag.中字": "yes"
    "tag.英字": "yes"
    "tag.DIY": "yes"
    "tag.原创": "yes"
    "tag.自购": "yes"
    "tag.MV母盘": "yes"
    "default": null
